apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-reporter
  labels:
    app: ip-reporter
spec:
  replicas: 1
  template:
    metadata:
      name: ip-reporter
      labels:
        app: ip-reporter
    spec:
      containers:
        - name: ip-reporter
          image: clearcodecn/ipreporter
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: ip-reporter
