apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/application/gitlab
    server: 192.168.0.106
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi