version: '3'
services:
  configsvr-repl-1-1:
    image: mongo:4.4
    command: |
      mongod --configsvr --replSet="configsvr-repl-1" --bind_ip_all --port="20001"  --dbpath=/data/db
    ports:
      - 20001:20001
    volumes:
      - c1:/data/db

  configsvr-repl-1-2:
    image: mongo:4.4
    command: |
      mongod --configsvr --replSet="configsvr-repl-1" --bind_ip_all --port="20002"  --dbpath=/data/db
    ports:
      - 20002:20002
    volumes:
      - c2:/data/db

  configsvr-repl-1-3:
    image: mongo:4.4
    command: |
      mongod --configsvr --replSet="configsvr-repl-1" --bind_ip_all --port="20003"  --dbpath=/data/db
    ports:
      - 20003:20003
    volumes:
      - c3:/data/db

volumes:
  c1:
  c2:
  c3: