apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/database/kafka
    server: 192.168.0.106
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /data/database/zookeeper
    server: 192.168.0.106
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi