apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "postgres"
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/database/postgres
    server: 192.168.0.106