apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis
  labels:
    app: redis
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "redis"
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/database/redis
    server: 192.168.0.106